services:
  postgres:
    container_name: groupi_postgres
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - 6500:5432
    volumes:
      - groupi_postgres_data:/var/lib/postgresql/data/

volumes:
  groupi_postgres_data:
