/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";
import type * as accountResolution_contracts from "../accountResolution/contracts.js";
import type * as accountResolution_model from "../accountResolution/model.js";
import type * as accountResolution_mutations from "../accountResolution/mutations.js";
import type * as accountResolution_queries from "../accountResolution/queries.js";
import type * as accountResolution_rest from "../accountResolution/rest.js";
import type * as accounts_mutations from "../accounts/mutations.js";
import type * as accounts_queries from "../accounts/queries.js";
import type * as addonTemplates_definition from "../addonTemplates/definition.js";
import type * as addonTemplates_mutations from "../addonTemplates/mutations.js";
import type * as addonTemplates_queries from "../addonTemplates/queries.js";
import type * as addonTemplates_rest from "../addonTemplates/rest.js";
import type * as addons_automations_conditions from "../addons/automations/conditions.js";
import type * as addons_automations_dispatch from "../addons/automations/dispatch.js";
import type * as addons_automations_engine from "../addons/automations/engine.js";
import type * as addons_automations_internalActions from "../addons/automations/internalActions.js";
import type * as addons_automations_internalMutations from "../addons/automations/internalMutations.js";
import type * as addons_automations_resolve from "../addons/automations/resolve.js";
import type * as addons_automations_types from "../addons/automations/types.js";
import type * as addons_context from "../addons/context.js";
import type * as addons_define from "../addons/define.js";
import type * as addons_handlers_bringList from "../addons/handlers/bringList.js";
import type * as addons_handlers_custom from "../addons/handlers/custom.js";
import type * as addons_handlers_discord from "../addons/handlers/discord.js";
import type * as addons_handlers_questionnaire from "../addons/handlers/questionnaire.js";
import type * as addons_handlers_reminders from "../addons/handlers/reminders.js";
import type * as addons_lifecycle from "../addons/lifecycle.js";
import type * as addons_mutations from "../addons/mutations.js";
import type * as addons_participation from "../addons/participation.js";
import type * as addons_queries from "../addons/queries.js";
import type * as addons_registry from "../addons/registry.js";
import type * as addons_types from "../addons/types.js";
import type * as admin_explorerQueries from "../admin/explorerQueries.js";
import type * as admin_mutations from "../admin/mutations.js";
import type * as admin_queries from "../admin/queries.js";
import type * as admin_queryBuilder from "../admin/queryBuilder.js";
import type * as ai_actions from "../ai/actions.js";
import type * as api_v1_index from "../api/v1/index.js";
import type * as api_v1_internal_addonConfiguration from "../api/v1/internal/addonConfiguration.js";
import type * as api_v1_internal_addons from "../api/v1/internal/addons.js";
import type * as api_v1_internal_admin from "../api/v1/internal/admin.js";
import type * as api_v1_internal_auth from "../api/v1/internal/auth.js";
import type * as api_v1_internal_availability from "../api/v1/internal/availability.js";
import type * as api_v1_internal_events from "../api/v1/internal/events.js";
import type * as api_v1_internal_friends from "../api/v1/internal/friends.js";
import type * as api_v1_internal_invites from "../api/v1/internal/invites.js";
import type * as api_v1_internal_members from "../api/v1/internal/members.js";
import type * as api_v1_internal_muting from "../api/v1/internal/muting.js";
import type * as api_v1_internal_notifications from "../api/v1/internal/notifications.js";
import type * as api_v1_internal_posts from "../api/v1/internal/posts.js";
import type * as api_v1_internal_profile from "../api/v1/internal/profile.js";
import type * as api_v1_internal_replies from "../api/v1/internal/replies.js";
import type * as api_v1_internal_reports from "../api/v1/internal/reports.js";
import type * as api_v1_internal_settings from "../api/v1/internal/settings.js";
import type * as api_v1_internal_social from "../api/v1/internal/social.js";
import type * as api_v1_internal_themes from "../api/v1/internal/themes.js";
import type * as api_v1_middleware_auth from "../api/v1/middleware/auth.js";
import type * as api_v1_routes_addons from "../api/v1/routes/addons.js";
import type * as api_v1_routes_admin from "../api/v1/routes/admin.js";
import type * as api_v1_routes_availability from "../api/v1/routes/availability.js";
import type * as api_v1_routes_events from "../api/v1/routes/events.js";
import type * as api_v1_routes_friends from "../api/v1/routes/friends.js";
import type * as api_v1_routes_invites from "../api/v1/routes/invites.js";
import type * as api_v1_routes_members from "../api/v1/routes/members.js";
import type * as api_v1_routes_muting from "../api/v1/routes/muting.js";
import type * as api_v1_routes_notifications from "../api/v1/routes/notifications.js";
import type * as api_v1_routes_posts from "../api/v1/routes/posts.js";
import type * as api_v1_routes_profile from "../api/v1/routes/profile.js";
import type * as api_v1_routes_replies from "../api/v1/routes/replies.js";
import type * as api_v1_routes_reports from "../api/v1/routes/reports.js";
import type * as api_v1_routes_settings from "../api/v1/routes/settings.js";
import type * as api_v1_routes_themes from "../api/v1/routes/themes.js";
import type * as api_v1_schemas_addons from "../api/v1/schemas/addons.js";
import type * as api_v1_schemas_admin from "../api/v1/schemas/admin.js";
import type * as api_v1_schemas_availability from "../api/v1/schemas/availability.js";
import type * as api_v1_schemas_common from "../api/v1/schemas/common.js";
import type * as api_v1_schemas_events from "../api/v1/schemas/events.js";
import type * as api_v1_schemas_friends from "../api/v1/schemas/friends.js";
import type * as api_v1_schemas_invites from "../api/v1/schemas/invites.js";
import type * as api_v1_schemas_members from "../api/v1/schemas/members.js";
import type * as api_v1_schemas_muting from "../api/v1/schemas/muting.js";
import type * as api_v1_schemas_notifications from "../api/v1/schemas/notifications.js";
import type * as api_v1_schemas_posts from "../api/v1/schemas/posts.js";
import type * as api_v1_schemas_profile from "../api/v1/schemas/profile.js";
import type * as api_v1_schemas_replies from "../api/v1/schemas/replies.js";
import type * as api_v1_schemas_reports from "../api/v1/schemas/reports.js";
import type * as api_v1_schemas_settings from "../api/v1/schemas/settings.js";
import type * as api_v1_schemas_themes from "../api/v1/schemas/themes.js";
import type * as api_v2_index from "../api/v2/index.js";
import type * as api_v2_routes_accountResolution from "../api/v2/routes/accountResolution.js";
import type * as api_v2_routes_addonDefinitions from "../api/v2/routes/addonDefinitions.js";
import type * as api_v2_routes_addonDiscord from "../api/v2/routes/addonDiscord.js";
import type * as api_v2_routes_addons from "../api/v2/routes/addons.js";
import type * as api_v2_routes_admin from "../api/v2/routes/admin.js";
import type * as api_v2_routes_availability from "../api/v2/routes/availability.js";
import type * as api_v2_routes_blocks from "../api/v2/routes/blocks.js";
import type * as api_v2_routes_cliAuth from "../api/v2/routes/cliAuth.js";
import type * as api_v2_routes_discussion from "../api/v2/routes/discussion.js";
import type * as api_v2_routes_eventApplications from "../api/v2/routes/eventApplications.js";
import type * as api_v2_routes_eventManagement from "../api/v2/routes/eventManagement.js";
import type * as api_v2_routes_eventTransfers from "../api/v2/routes/eventTransfers.js";
import type * as api_v2_routes_events from "../api/v2/routes/events.js";
import type * as api_v2_routes_friends from "../api/v2/routes/friends.js";
import type * as api_v2_routes_groupAnnouncements from "../api/v2/routes/groupAnnouncements.js";
import type * as api_v2_routes_groupApplications from "../api/v2/routes/groupApplications.js";
import type * as api_v2_routes_groupEventAudiences from "../api/v2/routes/groupEventAudiences.js";
import type * as api_v2_routes_groupForms from "../api/v2/routes/groupForms.js";
import type * as api_v2_routes_groupInvites from "../api/v2/routes/groupInvites.js";
import type * as api_v2_routes_groupModeration from "../api/v2/routes/groupModeration.js";
import type * as api_v2_routes_groupQuestionnaires from "../api/v2/routes/groupQuestionnaires.js";
import type * as api_v2_routes_groupTransfers from "../api/v2/routes/groupTransfers.js";
import type * as api_v2_routes_groups from "../api/v2/routes/groups.js";
import type * as api_v2_routes_images from "../api/v2/routes/images.js";
import type * as api_v2_routes_inviteLists from "../api/v2/routes/inviteLists.js";
import type * as api_v2_routes_invites from "../api/v2/routes/invites.js";
import type * as api_v2_routes_members from "../api/v2/routes/members.js";
import type * as api_v2_routes_muting from "../api/v2/routes/muting.js";
import type * as api_v2_routes_notifications from "../api/v2/routes/notifications.js";
import type * as api_v2_routes_posts from "../api/v2/routes/posts.js";
import type * as api_v2_routes_profile from "../api/v2/routes/profile.js";
import type * as api_v2_routes_replies from "../api/v2/routes/replies.js";
import type * as api_v2_routes_reports from "../api/v2/routes/reports.js";
import type * as api_v2_routes_settings from "../api/v2/routes/settings.js";
import type * as api_v2_routes_themes from "../api/v2/routes/themes.js";
import type * as api_v2_routes_uploads from "../api/v2/routes/uploads.js";
import type * as api_v2_schemas_addons from "../api/v2/schemas/addons.js";
import type * as api_v2_schemas_admin from "../api/v2/schemas/admin.js";
import type * as api_v2_schemas_availability from "../api/v2/schemas/availability.js";
import type * as api_v2_schemas_common from "../api/v2/schemas/common.js";
import type * as api_v2_schemas_eventLogistics from "../api/v2/schemas/eventLogistics.js";
import type * as api_v2_schemas_events from "../api/v2/schemas/events.js";
import type * as api_v2_schemas_friends from "../api/v2/schemas/friends.js";
import type * as api_v2_schemas_groupApplications from "../api/v2/schemas/groupApplications.js";
import type * as api_v2_schemas_groupInvites from "../api/v2/schemas/groupInvites.js";
import type * as api_v2_schemas_inviteLists from "../api/v2/schemas/inviteLists.js";
import type * as api_v2_schemas_invites from "../api/v2/schemas/invites.js";
import type * as api_v2_schemas_members from "../api/v2/schemas/members.js";
import type * as api_v2_schemas_muting from "../api/v2/schemas/muting.js";
import type * as api_v2_schemas_notifications from "../api/v2/schemas/notifications.js";
import type * as api_v2_schemas_posts from "../api/v2/schemas/posts.js";
import type * as api_v2_schemas_profile from "../api/v2/schemas/profile.js";
import type * as api_v2_schemas_replies from "../api/v2/schemas/replies.js";
import type * as api_v2_schemas_reports from "../api/v2/schemas/reports.js";
import type * as api_v2_schemas_settings from "../api/v2/schemas/settings.js";
import type * as api_v2_schemas_themes from "../api/v2/schemas/themes.js";
import type * as api_v2_validation from "../api/v2/validation.js";
import type * as appReview_http from "../appReview/http.js";
import type * as appReview_mutations from "../appReview/mutations.js";
import type * as appReview_queries from "../appReview/queries.js";
import type * as attachments_model from "../attachments/model.js";
import type * as attachments_mutations from "../attachments/mutations.js";
import type * as attachments_queries from "../attachments/queries.js";
import type * as auth from "../auth.js";
import type * as auth_queries from "../auth/queries.js";
import type * as availability_contracts from "../availability/contracts.js";
import type * as availability_model from "../availability/model.js";
import type * as availability_mutations from "../availability/mutations.js";
import type * as availability_queries from "../availability/queries.js";
import type * as availability_reads from "../availability/reads.js";
import type * as availability_rest from "../availability/rest.js";
import type * as availability_writes from "../availability/writes.js";
import type * as cliAuth_mutations from "../cliAuth/mutations.js";
import type * as convex__generated_api from "../convex/_generated/api.js";
import type * as convex__generated_server from "../convex/_generated/server.js";
import type * as crons from "../crons.js";
import type * as discord_actions from "../discord/actions.js";
import type * as discord_authorization from "../discord/authorization.js";
import type * as discord_cli from "../discord/cli.js";
import type * as discord_mutations from "../discord/mutations.js";
import type * as discord_permissions from "../discord/permissions.js";
import type * as discord_queries from "../discord/queries.js";
import type * as discord_userApi from "../discord/userApi.js";
import type * as discussion_rest from "../discussion/rest.js";
import type * as e2e_mutations from "../e2e/mutations.js";
import type * as email from "../email.js";
import type * as emails_mutations from "../emails/mutations.js";
import type * as emails_queries from "../emails/queries.js";
import type * as eventApplications_cleanup from "../eventApplications/cleanup.js";
import type * as eventApplications_contracts from "../eventApplications/contracts.js";
import type * as eventApplications_model from "../eventApplications/model.js";
import type * as eventApplications_mutations from "../eventApplications/mutations.js";
import type * as eventApplications_queries from "../eventApplications/queries.js";
import type * as eventApplications_rest from "../eventApplications/rest.js";
import type * as eventInvites_contracts from "../eventInvites/contracts.js";
import type * as eventInvites_eligibility from "../eventInvites/eligibility.js";
import type * as eventInvites_mutations from "../eventInvites/mutations.js";
import type * as eventInvites_queries from "../eventInvites/queries.js";
import type * as eventInvites_writes from "../eventInvites/writes.js";
import type * as eventTransfers_cleanup from "../eventTransfers/cleanup.js";
import type * as eventTransfers_model from "../eventTransfers/model.js";
import type * as eventTransfers_mutations from "../eventTransfers/mutations.js";
import type * as eventTransfers_queries from "../eventTransfers/queries.js";
import type * as eventTransfers_rest from "../eventTransfers/rest.js";
import type * as events_admission from "../events/admission.js";
import type * as events_admissionContracts from "../events/admissionContracts.js";
import type * as events_attendance from "../events/attendance.js";
import type * as events_management from "../events/management.js";
import type * as events_managementRest from "../events/managementRest.js";
import type * as events_mutations from "../events/mutations.js";
import type * as events_queries from "../events/queries.js";
import type * as events_rest from "../events/rest.js";
import type * as events_scheduling from "../events/scheduling.js";
import type * as events_validators from "../events/validators.js";
import type * as events_writes from "../events/writes.js";
import type * as files_imageRules from "../files/imageRules.js";
import type * as files_images from "../files/images.js";
import type * as files_mutations from "../files/mutations.js";
import type * as files_queries from "../files/queries.js";
import type * as files_uploads from "../files/uploads.js";
import type * as friends_mutations from "../friends/mutations.js";
import type * as friends_queries from "../friends/queries.js";
import type * as groupAnnouncements_actions from "../groupAnnouncements/actions.js";
import type * as groupAnnouncements_cleanup from "../groupAnnouncements/cleanup.js";
import type * as groupAnnouncements_contracts from "../groupAnnouncements/contracts.js";
import type * as groupAnnouncements_dispatch from "../groupAnnouncements/dispatch.js";
import type * as groupAnnouncements_model from "../groupAnnouncements/model.js";
import type * as groupAnnouncements_mutations from "../groupAnnouncements/mutations.js";
import type * as groupAnnouncements_queries from "../groupAnnouncements/queries.js";
import type * as groupAnnouncements_rest from "../groupAnnouncements/rest.js";
import type * as groupApplications_cleanup from "../groupApplications/cleanup.js";
import type * as groupApplications_contracts from "../groupApplications/contracts.js";
import type * as groupApplications_model from "../groupApplications/model.js";
import type * as groupApplications_mutations from "../groupApplications/mutations.js";
import type * as groupApplications_queries from "../groupApplications/queries.js";
import type * as groupApplications_rest from "../groupApplications/rest.js";
import type * as groupEventAudiences_access from "../groupEventAudiences/access.js";
import type * as groupEventAudiences_cleanup from "../groupEventAudiences/cleanup.js";
import type * as groupEventAudiences_contracts from "../groupEventAudiences/contracts.js";
import type * as groupEventAudiences_model from "../groupEventAudiences/model.js";
import type * as groupEventAudiences_mutations from "../groupEventAudiences/mutations.js";
import type * as groupEventAudiences_queries from "../groupEventAudiences/queries.js";
import type * as groupEventAudiences_rest from "../groupEventAudiences/rest.js";
import type * as groupForms_contracts from "../groupForms/contracts.js";
import type * as groupForms_model from "../groupForms/model.js";
import type * as groupForms_mutations from "../groupForms/mutations.js";
import type * as groupForms_queries from "../groupForms/queries.js";
import type * as groupForms_rest from "../groupForms/rest.js";
import type * as groupInvites_cleanup from "../groupInvites/cleanup.js";
import type * as groupInvites_contracts from "../groupInvites/contracts.js";
import type * as groupInvites_model from "../groupInvites/model.js";
import type * as groupInvites_mutations from "../groupInvites/mutations.js";
import type * as groupInvites_notificationProjection from "../groupInvites/notificationProjection.js";
import type * as groupInvites_queries from "../groupInvites/queries.js";
import type * as groupInvites_rest from "../groupInvites/rest.js";
import type * as groupModeration_cleanup from "../groupModeration/cleanup.js";
import type * as groupModeration_contracts from "../groupModeration/contracts.js";
import type * as groupModeration_model from "../groupModeration/model.js";
import type * as groupModeration_mutations from "../groupModeration/mutations.js";
import type * as groupModeration_queries from "../groupModeration/queries.js";
import type * as groupModeration_rest from "../groupModeration/rest.js";
import type * as groupQuestionnaires_actions from "../groupQuestionnaires/actions.js";
import type * as groupQuestionnaires_cleanup from "../groupQuestionnaires/cleanup.js";
import type * as groupQuestionnaires_contracts from "../groupQuestionnaires/contracts.js";
import type * as groupQuestionnaires_model from "../groupQuestionnaires/model.js";
import type * as groupQuestionnaires_mutations from "../groupQuestionnaires/mutations.js";
import type * as groupQuestionnaires_notificationJobs from "../groupQuestionnaires/notificationJobs.js";
import type * as groupQuestionnaires_notifications from "../groupQuestionnaires/notifications.js";
import type * as groupQuestionnaires_queries from "../groupQuestionnaires/queries.js";
import type * as groupQuestionnaires_rest from "../groupQuestionnaires/rest.js";
import type * as groupTools_cleanup from "../groupTools/cleanup.js";
import type * as groupTools_contracts from "../groupTools/contracts.js";
import type * as groupTools_mutations from "../groupTools/mutations.js";
import type * as groupTools_policy from "../groupTools/policy.js";
import type * as groupTools_queries from "../groupTools/queries.js";
import type * as groupTransfers_cleanup from "../groupTransfers/cleanup.js";
import type * as groupTransfers_contracts from "../groupTransfers/contracts.js";
import type * as groupTransfers_model from "../groupTransfers/model.js";
import type * as groupTransfers_mutations from "../groupTransfers/mutations.js";
import type * as groupTransfers_queries from "../groupTransfers/queries.js";
import type * as groupTransfers_rest from "../groupTransfers/rest.js";
import type * as groups_admission from "../groups/admission.js";
import type * as groups_cleanup from "../groups/cleanup.js";
import type * as groups_contentAccess from "../groups/contentAccess.js";
import type * as groups_contracts from "../groups/contracts.js";
import type * as groups_model from "../groups/model.js";
import type * as groups_mutations from "../groups/mutations.js";
import type * as groups_policy from "../groups/policy.js";
import type * as groups_queries from "../groups/queries.js";
import type * as groups_rest from "../groups/rest.js";
import type * as http from "../http.js";
import type * as inviteLists_contracts from "../inviteLists/contracts.js";
import type * as inviteLists_model from "../inviteLists/model.js";
import type * as inviteLists_mutations from "../inviteLists/mutations.js";
import type * as inviteLists_queries from "../inviteLists/queries.js";
import type * as inviteLists_rest from "../inviteLists/rest.js";
import type * as inviteLists_sending from "../inviteLists/sending.js";
import type * as invites_actions from "../invites/actions.js";
import type * as invites_contracts from "../invites/contracts.js";
import type * as invites_mutations from "../invites/mutations.js";
import type * as invites_permissions from "../invites/permissions.js";
import type * as invites_queries from "../invites/queries.js";
import type * as invites_rest from "../invites/rest.js";
import type * as invites_writes from "../invites/writes.js";
import type * as lib_cascade from "../lib/cascade.js";
import type * as lib_constants from "../lib/constants.js";
import type * as lib_discussionAccess from "../lib/discussionAccess.js";
import type * as lib_discussionContent from "../lib/discussionContent.js";
import type * as lib_friends from "../lib/friends.js";
import type * as lib_gdl_parser from "../lib/gdl_parser.js";
import type * as lib_memberCount from "../lib/memberCount.js";
import type * as lib_notifications from "../lib/notifications.js";
import type * as lib_passkeyConfig from "../lib/passkeyConfig.js";
import type * as lib_privacy from "../lib/privacy.js";
import type * as lib_requestId from "../lib/requestId.js";
import type * as migration_actions from "../migration/actions.js";
import type * as migration_backfillMemberCount from "../migration/backfillMemberCount.js";
import type * as migration_claim from "../migration/claim.js";
import type * as migration_dedupeAvailabilities from "../migration/dedupeAvailabilities.js";
import type * as migration_index from "../migration/index.js";
import type * as migration_mutations from "../migration/mutations.js";
import type * as migration_uploadAndMigrate from "../migration/uploadAndMigrate.js";
import type * as muting_model from "../muting/model.js";
import type * as muting_mutations from "../muting/mutations.js";
import type * as muting_queries from "../muting/queries.js";
import type * as notifications_actions from "../notifications/actions.js";
import type * as notifications_model from "../notifications/model.js";
import type * as notifications_mutations from "../notifications/mutations.js";
import type * as notifications_queries from "../notifications/queries.js";
import type * as posts_mutations from "../posts/mutations.js";
import type * as posts_queries from "../posts/queries.js";
import type * as presence from "../presence.js";
import type * as pushNotifications_actions from "../pushNotifications/actions.js";
import type * as pushNotifications_constants from "../pushNotifications/constants.js";
import type * as pushNotifications_mutations from "../pushNotifications/mutations.js";
import type * as pushNotifications_queries from "../pushNotifications/queries.js";
import type * as pushNotifications_retention from "../pushNotifications/retention.js";
import type * as reminderOptOuts_mutations from "../reminderOptOuts/mutations.js";
import type * as reminderOptOuts_queries from "../reminderOptOuts/queries.js";
import type * as reminders_index from "../reminders/index.js";
import type * as reminders_mutations from "../reminders/mutations.js";
import type * as replies_mutations from "../replies/mutations.js";
import type * as replies_queries from "../replies/queries.js";
import type * as reports_adminMutations from "../reports/adminMutations.js";
import type * as reports_mutations from "../reports/mutations.js";
import type * as reports_queries from "../reports/queries.js";
import type * as settings_mutations from "../settings/mutations.js";
import type * as settings_queries from "../settings/queries.js";
import type * as tests_image_fixtures from "../tests/image_fixtures.js";
import type * as tests_test_helpers from "../tests/test_helpers.js";
import type * as themes_mutations from "../themes/mutations.js";
import type * as themes_queries from "../themes/queries.js";
import type * as types from "../types.js";
import type * as users_mutations from "../users/mutations.js";
import type * as users_queries from "../users/queries.js";

/**
 * A utility for referencing Convex functions in your app's API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
declare const fullApi: ApiFromModules<{
  "accountResolution/contracts": typeof accountResolution_contracts;
  "accountResolution/model": typeof accountResolution_model;
  "accountResolution/mutations": typeof accountResolution_mutations;
  "accountResolution/queries": typeof accountResolution_queries;
  "accountResolution/rest": typeof accountResolution_rest;
  "accounts/mutations": typeof accounts_mutations;
  "accounts/queries": typeof accounts_queries;
  "addonTemplates/definition": typeof addonTemplates_definition;
  "addonTemplates/mutations": typeof addonTemplates_mutations;
  "addonTemplates/queries": typeof addonTemplates_queries;
  "addonTemplates/rest": typeof addonTemplates_rest;
  "addons/automations/conditions": typeof addons_automations_conditions;
  "addons/automations/dispatch": typeof addons_automations_dispatch;
  "addons/automations/engine": typeof addons_automations_engine;
  "addons/automations/internalActions": typeof addons_automations_internalActions;
  "addons/automations/internalMutations": typeof addons_automations_internalMutations;
  "addons/automations/resolve": typeof addons_automations_resolve;
  "addons/automations/types": typeof addons_automations_types;
  "addons/context": typeof addons_context;
  "addons/define": typeof addons_define;
  "addons/handlers/bringList": typeof addons_handlers_bringList;
  "addons/handlers/custom": typeof addons_handlers_custom;
  "addons/handlers/discord": typeof addons_handlers_discord;
  "addons/handlers/questionnaire": typeof addons_handlers_questionnaire;
  "addons/handlers/reminders": typeof addons_handlers_reminders;
  "addons/lifecycle": typeof addons_lifecycle;
  "addons/mutations": typeof addons_mutations;
  "addons/participation": typeof addons_participation;
  "addons/queries": typeof addons_queries;
  "addons/registry": typeof addons_registry;
  "addons/types": typeof addons_types;
  "admin/explorerQueries": typeof admin_explorerQueries;
  "admin/mutations": typeof admin_mutations;
  "admin/queries": typeof admin_queries;
  "admin/queryBuilder": typeof admin_queryBuilder;
  "ai/actions": typeof ai_actions;
  "api/v1/index": typeof api_v1_index;
  "api/v1/internal/addonConfiguration": typeof api_v1_internal_addonConfiguration;
  "api/v1/internal/addons": typeof api_v1_internal_addons;
  "api/v1/internal/admin": typeof api_v1_internal_admin;
  "api/v1/internal/auth": typeof api_v1_internal_auth;
  "api/v1/internal/availability": typeof api_v1_internal_availability;
  "api/v1/internal/events": typeof api_v1_internal_events;
  "api/v1/internal/friends": typeof api_v1_internal_friends;
  "api/v1/internal/invites": typeof api_v1_internal_invites;
  "api/v1/internal/members": typeof api_v1_internal_members;
  "api/v1/internal/muting": typeof api_v1_internal_muting;
  "api/v1/internal/notifications": typeof api_v1_internal_notifications;
  "api/v1/internal/posts": typeof api_v1_internal_posts;
  "api/v1/internal/profile": typeof api_v1_internal_profile;
  "api/v1/internal/replies": typeof api_v1_internal_replies;
  "api/v1/internal/reports": typeof api_v1_internal_reports;
  "api/v1/internal/settings": typeof api_v1_internal_settings;
  "api/v1/internal/social": typeof api_v1_internal_social;
  "api/v1/internal/themes": typeof api_v1_internal_themes;
  "api/v1/middleware/auth": typeof api_v1_middleware_auth;
  "api/v1/routes/addons": typeof api_v1_routes_addons;
  "api/v1/routes/admin": typeof api_v1_routes_admin;
  "api/v1/routes/availability": typeof api_v1_routes_availability;
  "api/v1/routes/events": typeof api_v1_routes_events;
  "api/v1/routes/friends": typeof api_v1_routes_friends;
  "api/v1/routes/invites": typeof api_v1_routes_invites;
  "api/v1/routes/members": typeof api_v1_routes_members;
  "api/v1/routes/muting": typeof api_v1_routes_muting;
  "api/v1/routes/notifications": typeof api_v1_routes_notifications;
  "api/v1/routes/posts": typeof api_v1_routes_posts;
  "api/v1/routes/profile": typeof api_v1_routes_profile;
  "api/v1/routes/replies": typeof api_v1_routes_replies;
  "api/v1/routes/reports": typeof api_v1_routes_reports;
  "api/v1/routes/settings": typeof api_v1_routes_settings;
  "api/v1/routes/themes": typeof api_v1_routes_themes;
  "api/v1/schemas/addons": typeof api_v1_schemas_addons;
  "api/v1/schemas/admin": typeof api_v1_schemas_admin;
  "api/v1/schemas/availability": typeof api_v1_schemas_availability;
  "api/v1/schemas/common": typeof api_v1_schemas_common;
  "api/v1/schemas/events": typeof api_v1_schemas_events;
  "api/v1/schemas/friends": typeof api_v1_schemas_friends;
  "api/v1/schemas/invites": typeof api_v1_schemas_invites;
  "api/v1/schemas/members": typeof api_v1_schemas_members;
  "api/v1/schemas/muting": typeof api_v1_schemas_muting;
  "api/v1/schemas/notifications": typeof api_v1_schemas_notifications;
  "api/v1/schemas/posts": typeof api_v1_schemas_posts;
  "api/v1/schemas/profile": typeof api_v1_schemas_profile;
  "api/v1/schemas/replies": typeof api_v1_schemas_replies;
  "api/v1/schemas/reports": typeof api_v1_schemas_reports;
  "api/v1/schemas/settings": typeof api_v1_schemas_settings;
  "api/v1/schemas/themes": typeof api_v1_schemas_themes;
  "api/v2/index": typeof api_v2_index;
  "api/v2/routes/accountResolution": typeof api_v2_routes_accountResolution;
  "api/v2/routes/addonDefinitions": typeof api_v2_routes_addonDefinitions;
  "api/v2/routes/addonDiscord": typeof api_v2_routes_addonDiscord;
  "api/v2/routes/addons": typeof api_v2_routes_addons;
  "api/v2/routes/admin": typeof api_v2_routes_admin;
  "api/v2/routes/availability": typeof api_v2_routes_availability;
  "api/v2/routes/blocks": typeof api_v2_routes_blocks;
  "api/v2/routes/cliAuth": typeof api_v2_routes_cliAuth;
  "api/v2/routes/discussion": typeof api_v2_routes_discussion;
  "api/v2/routes/eventApplications": typeof api_v2_routes_eventApplications;
  "api/v2/routes/eventManagement": typeof api_v2_routes_eventManagement;
  "api/v2/routes/eventTransfers": typeof api_v2_routes_eventTransfers;
  "api/v2/routes/events": typeof api_v2_routes_events;
  "api/v2/routes/friends": typeof api_v2_routes_friends;
  "api/v2/routes/groupAnnouncements": typeof api_v2_routes_groupAnnouncements;
  "api/v2/routes/groupApplications": typeof api_v2_routes_groupApplications;
  "api/v2/routes/groupEventAudiences": typeof api_v2_routes_groupEventAudiences;
  "api/v2/routes/groupForms": typeof api_v2_routes_groupForms;
  "api/v2/routes/groupInvites": typeof api_v2_routes_groupInvites;
  "api/v2/routes/groupModeration": typeof api_v2_routes_groupModeration;
  "api/v2/routes/groupQuestionnaires": typeof api_v2_routes_groupQuestionnaires;
  "api/v2/routes/groupTransfers": typeof api_v2_routes_groupTransfers;
  "api/v2/routes/groups": typeof api_v2_routes_groups;
  "api/v2/routes/images": typeof api_v2_routes_images;
  "api/v2/routes/inviteLists": typeof api_v2_routes_inviteLists;
  "api/v2/routes/invites": typeof api_v2_routes_invites;
  "api/v2/routes/members": typeof api_v2_routes_members;
  "api/v2/routes/muting": typeof api_v2_routes_muting;
  "api/v2/routes/notifications": typeof api_v2_routes_notifications;
  "api/v2/routes/posts": typeof api_v2_routes_posts;
  "api/v2/routes/profile": typeof api_v2_routes_profile;
  "api/v2/routes/replies": typeof api_v2_routes_replies;
  "api/v2/routes/reports": typeof api_v2_routes_reports;
  "api/v2/routes/settings": typeof api_v2_routes_settings;
  "api/v2/routes/themes": typeof api_v2_routes_themes;
  "api/v2/routes/uploads": typeof api_v2_routes_uploads;
  "api/v2/schemas/addons": typeof api_v2_schemas_addons;
  "api/v2/schemas/admin": typeof api_v2_schemas_admin;
  "api/v2/schemas/availability": typeof api_v2_schemas_availability;
  "api/v2/schemas/common": typeof api_v2_schemas_common;
  "api/v2/schemas/eventLogistics": typeof api_v2_schemas_eventLogistics;
  "api/v2/schemas/events": typeof api_v2_schemas_events;
  "api/v2/schemas/friends": typeof api_v2_schemas_friends;
  "api/v2/schemas/groupApplications": typeof api_v2_schemas_groupApplications;
  "api/v2/schemas/groupInvites": typeof api_v2_schemas_groupInvites;
  "api/v2/schemas/inviteLists": typeof api_v2_schemas_inviteLists;
  "api/v2/schemas/invites": typeof api_v2_schemas_invites;
  "api/v2/schemas/members": typeof api_v2_schemas_members;
  "api/v2/schemas/muting": typeof api_v2_schemas_muting;
  "api/v2/schemas/notifications": typeof api_v2_schemas_notifications;
  "api/v2/schemas/posts": typeof api_v2_schemas_posts;
  "api/v2/schemas/profile": typeof api_v2_schemas_profile;
  "api/v2/schemas/replies": typeof api_v2_schemas_replies;
  "api/v2/schemas/reports": typeof api_v2_schemas_reports;
  "api/v2/schemas/settings": typeof api_v2_schemas_settings;
  "api/v2/schemas/themes": typeof api_v2_schemas_themes;
  "api/v2/validation": typeof api_v2_validation;
  "appReview/http": typeof appReview_http;
  "appReview/mutations": typeof appReview_mutations;
  "appReview/queries": typeof appReview_queries;
  "attachments/model": typeof attachments_model;
  "attachments/mutations": typeof attachments_mutations;
  "attachments/queries": typeof attachments_queries;
  auth: typeof auth;
  "auth/queries": typeof auth_queries;
  "availability/contracts": typeof availability_contracts;
  "availability/model": typeof availability_model;
  "availability/mutations": typeof availability_mutations;
  "availability/queries": typeof availability_queries;
  "availability/reads": typeof availability_reads;
  "availability/rest": typeof availability_rest;
  "availability/writes": typeof availability_writes;
  "cliAuth/mutations": typeof cliAuth_mutations;
  "convex/_generated/api": typeof convex__generated_api;
  "convex/_generated/server": typeof convex__generated_server;
  crons: typeof crons;
  "discord/actions": typeof discord_actions;
  "discord/authorization": typeof discord_authorization;
  "discord/cli": typeof discord_cli;
  "discord/mutations": typeof discord_mutations;
  "discord/permissions": typeof discord_permissions;
  "discord/queries": typeof discord_queries;
  "discord/userApi": typeof discord_userApi;
  "discussion/rest": typeof discussion_rest;
  "e2e/mutations": typeof e2e_mutations;
  email: typeof email;
  "emails/mutations": typeof emails_mutations;
  "emails/queries": typeof emails_queries;
  "eventApplications/cleanup": typeof eventApplications_cleanup;
  "eventApplications/contracts": typeof eventApplications_contracts;
  "eventApplications/model": typeof eventApplications_model;
  "eventApplications/mutations": typeof eventApplications_mutations;
  "eventApplications/queries": typeof eventApplications_queries;
  "eventApplications/rest": typeof eventApplications_rest;
  "eventInvites/contracts": typeof eventInvites_contracts;
  "eventInvites/eligibility": typeof eventInvites_eligibility;
  "eventInvites/mutations": typeof eventInvites_mutations;
  "eventInvites/queries": typeof eventInvites_queries;
  "eventInvites/writes": typeof eventInvites_writes;
  "eventTransfers/cleanup": typeof eventTransfers_cleanup;
  "eventTransfers/model": typeof eventTransfers_model;
  "eventTransfers/mutations": typeof eventTransfers_mutations;
  "eventTransfers/queries": typeof eventTransfers_queries;
  "eventTransfers/rest": typeof eventTransfers_rest;
  "events/admission": typeof events_admission;
  "events/admissionContracts": typeof events_admissionContracts;
  "events/attendance": typeof events_attendance;
  "events/management": typeof events_management;
  "events/managementRest": typeof events_managementRest;
  "events/mutations": typeof events_mutations;
  "events/queries": typeof events_queries;
  "events/rest": typeof events_rest;
  "events/scheduling": typeof events_scheduling;
  "events/validators": typeof events_validators;
  "events/writes": typeof events_writes;
  "files/imageRules": typeof files_imageRules;
  "files/images": typeof files_images;
  "files/mutations": typeof files_mutations;
  "files/queries": typeof files_queries;
  "files/uploads": typeof files_uploads;
  "friends/mutations": typeof friends_mutations;
  "friends/queries": typeof friends_queries;
  "groupAnnouncements/actions": typeof groupAnnouncements_actions;
  "groupAnnouncements/cleanup": typeof groupAnnouncements_cleanup;
  "groupAnnouncements/contracts": typeof groupAnnouncements_contracts;
  "groupAnnouncements/dispatch": typeof groupAnnouncements_dispatch;
  "groupAnnouncements/model": typeof groupAnnouncements_model;
  "groupAnnouncements/mutations": typeof groupAnnouncements_mutations;
  "groupAnnouncements/queries": typeof groupAnnouncements_queries;
  "groupAnnouncements/rest": typeof groupAnnouncements_rest;
  "groupApplications/cleanup": typeof groupApplications_cleanup;
  "groupApplications/contracts": typeof groupApplications_contracts;
  "groupApplications/model": typeof groupApplications_model;
  "groupApplications/mutations": typeof groupApplications_mutations;
  "groupApplications/queries": typeof groupApplications_queries;
  "groupApplications/rest": typeof groupApplications_rest;
  "groupEventAudiences/access": typeof groupEventAudiences_access;
  "groupEventAudiences/cleanup": typeof groupEventAudiences_cleanup;
  "groupEventAudiences/contracts": typeof groupEventAudiences_contracts;
  "groupEventAudiences/model": typeof groupEventAudiences_model;
  "groupEventAudiences/mutations": typeof groupEventAudiences_mutations;
  "groupEventAudiences/queries": typeof groupEventAudiences_queries;
  "groupEventAudiences/rest": typeof groupEventAudiences_rest;
  "groupForms/contracts": typeof groupForms_contracts;
  "groupForms/model": typeof groupForms_model;
  "groupForms/mutations": typeof groupForms_mutations;
  "groupForms/queries": typeof groupForms_queries;
  "groupForms/rest": typeof groupForms_rest;
  "groupInvites/cleanup": typeof groupInvites_cleanup;
  "groupInvites/contracts": typeof groupInvites_contracts;
  "groupInvites/model": typeof groupInvites_model;
  "groupInvites/mutations": typeof groupInvites_mutations;
  "groupInvites/notificationProjection": typeof groupInvites_notificationProjection;
  "groupInvites/queries": typeof groupInvites_queries;
  "groupInvites/rest": typeof groupInvites_rest;
  "groupModeration/cleanup": typeof groupModeration_cleanup;
  "groupModeration/contracts": typeof groupModeration_contracts;
  "groupModeration/model": typeof groupModeration_model;
  "groupModeration/mutations": typeof groupModeration_mutations;
  "groupModeration/queries": typeof groupModeration_queries;
  "groupModeration/rest": typeof groupModeration_rest;
  "groupQuestionnaires/actions": typeof groupQuestionnaires_actions;
  "groupQuestionnaires/cleanup": typeof groupQuestionnaires_cleanup;
  "groupQuestionnaires/contracts": typeof groupQuestionnaires_contracts;
  "groupQuestionnaires/model": typeof groupQuestionnaires_model;
  "groupQuestionnaires/mutations": typeof groupQuestionnaires_mutations;
  "groupQuestionnaires/notificationJobs": typeof groupQuestionnaires_notificationJobs;
  "groupQuestionnaires/notifications": typeof groupQuestionnaires_notifications;
  "groupQuestionnaires/queries": typeof groupQuestionnaires_queries;
  "groupQuestionnaires/rest": typeof groupQuestionnaires_rest;
  "groupTools/cleanup": typeof groupTools_cleanup;
  "groupTools/contracts": typeof groupTools_contracts;
  "groupTools/mutations": typeof groupTools_mutations;
  "groupTools/policy": typeof groupTools_policy;
  "groupTools/queries": typeof groupTools_queries;
  "groupTransfers/cleanup": typeof groupTransfers_cleanup;
  "groupTransfers/contracts": typeof groupTransfers_contracts;
  "groupTransfers/model": typeof groupTransfers_model;
  "groupTransfers/mutations": typeof groupTransfers_mutations;
  "groupTransfers/queries": typeof groupTransfers_queries;
  "groupTransfers/rest": typeof groupTransfers_rest;
  "groups/admission": typeof groups_admission;
  "groups/cleanup": typeof groups_cleanup;
  "groups/contentAccess": typeof groups_contentAccess;
  "groups/contracts": typeof groups_contracts;
  "groups/model": typeof groups_model;
  "groups/mutations": typeof groups_mutations;
  "groups/policy": typeof groups_policy;
  "groups/queries": typeof groups_queries;
  "groups/rest": typeof groups_rest;
  http: typeof http;
  "inviteLists/contracts": typeof inviteLists_contracts;
  "inviteLists/model": typeof inviteLists_model;
  "inviteLists/mutations": typeof inviteLists_mutations;
  "inviteLists/queries": typeof inviteLists_queries;
  "inviteLists/rest": typeof inviteLists_rest;
  "inviteLists/sending": typeof inviteLists_sending;
  "invites/actions": typeof invites_actions;
  "invites/contracts": typeof invites_contracts;
  "invites/mutations": typeof invites_mutations;
  "invites/permissions": typeof invites_permissions;
  "invites/queries": typeof invites_queries;
  "invites/rest": typeof invites_rest;
  "invites/writes": typeof invites_writes;
  "lib/cascade": typeof lib_cascade;
  "lib/constants": typeof lib_constants;
  "lib/discussionAccess": typeof lib_discussionAccess;
  "lib/discussionContent": typeof lib_discussionContent;
  "lib/friends": typeof lib_friends;
  "lib/gdl_parser": typeof lib_gdl_parser;
  "lib/memberCount": typeof lib_memberCount;
  "lib/notifications": typeof lib_notifications;
  "lib/passkeyConfig": typeof lib_passkeyConfig;
  "lib/privacy": typeof lib_privacy;
  "lib/requestId": typeof lib_requestId;
  "migration/actions": typeof migration_actions;
  "migration/backfillMemberCount": typeof migration_backfillMemberCount;
  "migration/claim": typeof migration_claim;
  "migration/dedupeAvailabilities": typeof migration_dedupeAvailabilities;
  "migration/index": typeof migration_index;
  "migration/mutations": typeof migration_mutations;
  "migration/uploadAndMigrate": typeof migration_uploadAndMigrate;
  "muting/model": typeof muting_model;
  "muting/mutations": typeof muting_mutations;
  "muting/queries": typeof muting_queries;
  "notifications/actions": typeof notifications_actions;
  "notifications/model": typeof notifications_model;
  "notifications/mutations": typeof notifications_mutations;
  "notifications/queries": typeof notifications_queries;
  "posts/mutations": typeof posts_mutations;
  "posts/queries": typeof posts_queries;
  presence: typeof presence;
  "pushNotifications/actions": typeof pushNotifications_actions;
  "pushNotifications/constants": typeof pushNotifications_constants;
  "pushNotifications/mutations": typeof pushNotifications_mutations;
  "pushNotifications/queries": typeof pushNotifications_queries;
  "pushNotifications/retention": typeof pushNotifications_retention;
  "reminderOptOuts/mutations": typeof reminderOptOuts_mutations;
  "reminderOptOuts/queries": typeof reminderOptOuts_queries;
  "reminders/index": typeof reminders_index;
  "reminders/mutations": typeof reminders_mutations;
  "replies/mutations": typeof replies_mutations;
  "replies/queries": typeof replies_queries;
  "reports/adminMutations": typeof reports_adminMutations;
  "reports/mutations": typeof reports_mutations;
  "reports/queries": typeof reports_queries;
  "settings/mutations": typeof settings_mutations;
  "settings/queries": typeof settings_queries;
  "tests/image_fixtures": typeof tests_image_fixtures;
  "tests/test_helpers": typeof tests_test_helpers;
  "themes/mutations": typeof themes_mutations;
  "themes/queries": typeof themes_queries;
  types: typeof types;
  "users/mutations": typeof users_mutations;
  "users/queries": typeof users_queries;
}>;
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;

export declare const components: {
  presence: import("@convex-dev/presence/_generated/component.js").ComponentApi<"presence">;
  betterAuth: import("../betterAuth/_generated/component.js").ComponentApi<"betterAuth">;
  resend: import("@convex-dev/resend/_generated/component.js").ComponentApi<"resend">;
};
