/** A browser authorization request generated by the waiting CLI process. */
export function parseCliAuthRequest(params: Pick<URLSearchParams, 'getAll'>) {
  const names = ['callbackPort', 'state', 'challenge'] as const;
  if (names.some(name => params.getAll(name).length !== 1)) return null;
  const [port] = params.getAll('callbackPort');
  const [state] = params.getAll('state');
  const [challenge] = params.getAll('challenge');
  if (!/^[1-9]\d{0,4}$/.test(port) || Number(port) > 65535) return null;
  if (!/^[A-Za-z0-9_-]{43}$/.test(state)) return null;
  if (!/^[A-Za-z0-9_-]{43}$/.test(challenge)) return null;
  return { callbackPort: Number(port), state, challenge };
}

export function cliAuthReturnPath(
  request: NonNullable<ReturnType<typeof parseCliAuthRequest>>
) {
  const params = new URLSearchParams({
    callbackPort: String(request.callbackPort),
    state: request.state,
    challenge: request.challenge,
  });
  return `/cli-auth?${params}`;
}

export function cliCallbackUrl(
  request: NonNullable<ReturnType<typeof parseCliAuthRequest>>,
  result: { code: string } | { error: 'access_denied' }
) {
  const url = new URL('http://127.0.0.1/callback');
  url.port = String(request.callbackPort);
  url.searchParams.set('state', request.state);
  if ('code' in result) url.searchParams.set('code', result.code);
  else url.searchParams.set('error', result.error);
  return url.toString();
}

export function navigateToCli(url: string) {
  // Replace the authorization URL so back navigation cannot repeat consent.
  window.location.replace(url);
}
