import { defineConfig } from 'vitest/config';

export default defineConfig({
  test: {
    globals: true,
    include: [
      'src/**/*.test.ts',
      'src/**/*.test.tsx',
      'app/**/*.test.ts',
      'app/**/*.test.tsx',
      '__tests__/**/*.test.ts',
      '__tests__/**/*.test.tsx',
    ],
    exclude: ['node_modules', 'dist', '.expo', 'android', 'ios', 'coverage'],
    environment: 'node',
    setupFiles: ['./test-setup.ts'],
    server: {
      deps: {
        // Prevent Vitest from trying to parse React Native's Flow syntax
        external: [
          'react-native',
          'react-native-reanimated',
          'react-native-worklets',
          'react-native-gesture-handler',
          'react-native-screens',
          'react-native-safe-area-context',
          'react-native-toast-message',
          'expo-router',
          'expo-secure-store',
          'expo-constants',
          'expo-splash-screen',
          'expo-status-bar',
          'expo-linking',
          '@expo/vector-icons',
          '@convex-dev/better-auth',
          'better-auth',
          '@testing-library/react-native',
        ],
      },
    },
    coverage: {
      provider: 'v8',
      reporter: ['text', 'html', 'lcov', 'json'],
      reportsDirectory: './coverage',
      exclude: [
        'node_modules/**',
        'dist/**',
        '.expo/**',
        'android/**',
        'ios/**',
        'src/**/*.test.ts',
        'src/**/*.test.tsx',
        'app/**/*.test.ts',
        'app/**/*.test.tsx',
        '__tests__/**',
        'test-helpers.tsx',
        'test-setup.ts',
        '**/*.config.*',
        '**/*.d.ts',
        'coverage/**',
        'expo/**',
        'app.config.ts',
        'babel.config.js',
      ],
      thresholds: {
        global: {
          branches: 70,
          functions: 70,
          lines: 70,
          statements: 70,
        },
      },
      include: ['src/**/*.{ts,tsx}', 'app/**/*.{ts,tsx}'],
    },
  },
  resolve: {
    alias: {
      '@': './src',
      '@/components': './src/components',
      '@/lib': './src/lib',
      '@/hooks': './src/hooks',
      '@/context': './src/context',
      '@/theme': './src/theme',
      '@/providers': './src/providers',
      'convex/_generated': '../../convex/_generated',
    },
  },
});
